spring:
  mvc:
    contentnegotiation:
      media-types:
        json: application/json
        yaml: application/yaml
        csv: text/csv
      favor-path-extension: true
    pathmatch:
      use-registered-suffix-pattern: true
